data:
  allowed_extensions:
  - .png
  csv_key_column: novo nome
  csv_label_columns:
  - tipo
  - projeto original
  - autor
  csv_path: /home/munif/dataset/100Dataset_encrypted_fixed_size/catalogo.csv
  enforce_size: validate
  expected_size:
  - 128
  - 128
  grayscale_mode: single
  input_channels: 1
  root_dir: /home/munif/dataset/100Dataset_encrypted_fixed_size
model:
  arch: efficientnet_b0
  freeze_backbone: false
  pretrained: true
optim:
  lr: 1e-3
  momentum: 0.9
  name: adam
  weight_decay: 1e-4
sampling:
  max_samples_per_class: 5000
  min_samples_per_class: 100
scheduler:
  gamma: 0.1
  name: null
  step_size: 5
seed: 18081975
split:
  test: 0.15
  train: 0.7
  val: 0.15
train:
  amp: true
  batch_size: 128
  early_stopping_patience: 5
  epochs: 10
  num_workers: 4
transforms:
  mode: normalize
  normalize:
    mean:
    - 0.5
    std:
    - 0.5
xai:
  enabled: true
  per_class_samples: 20
