seed: 18081975

data:
  root_dir: "/home/munif/dataset/100Dataset_encrypted_fixed_size"
  csv_path: "/home/munif/dataset/100Dataset_encrypted_fixed_size/catalogo.csv"
  csv_key_column: "novo nome"
  csv_label_columns: ["tipo", "projeto original", "autor"]
  allowed_extensions: [".png"]
  expected_size: [128, 128]
  enforce_size: "validate"          # "validate" | "resize_if_mismatch" | "error"
  input_channels: 1                  # grayscale
  grayscale_mode: "single"          # "single" | "replicate_to_rgb"

sampling:
  min_samples_per_class: 100         # classes with fewer will be ignored
  max_samples_per_class: 5000       # classes with more will be randomly downsampled

split:
  train: 0.7
  val: 0.15
  test: 0.15

transforms:
  mode: "to_tensor_only"            # "none" | "to_tensor_only" | "normalize"
  normalize:
    mean: [0.5]                     # only used when mode=="normalize"
    std: [0.5]

model:
  arch: "resnet18"                  # "resnet18" | "efficientnet_b0" | "vit_b_16"
  pretrained: true
  freeze_backbone: false

train:
  epochs: 5              # inteiro (ok p/ parser). Early stopping decide o fim.
  batch_size: 64
  grad_accum_steps: 2
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  amp: "cuda"
  cudnn_benchmark: true
  compile: true
  early_stopping_patience:  5

optim:
  name: "adam"                      # "adam" | "sgd"
  lr: 1e-3
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  name: null                        # "steplr" | null
  step_size: 5
  gamma: 0.1

xai:
  enabled: true
  per_class_samples: 20
